/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderStatus = IDL.Variant({
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'voided' : IDL.Null,
});
export const Time = IDL.Int;
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'tax' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'timestamp' : Time,
  'items' : IDL.Vec(CartItem),
  'subtotal' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQty' : IDL.Nat,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'priceCents' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItemToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkoutCart' : IDL.Func([], [IDL.Nat], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCompletedOrders' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'removeItemFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCartItemQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderStatus = IDL.Variant({
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'voided' : IDL.Null,
  });
  const Time = IDL.Int;
  const CartItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'tax' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'timestamp' : Time,
    'items' : IDL.Vec(CartItem),
    'subtotal' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQty' : IDL.Nat,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'priceCents' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItemToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkoutCart' : IDL.Func([], [IDL.Nat], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCompletedOrders' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'removeItemFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCartItemQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };